import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./(auth)/context";
import Notification from "./components/toast";
import { CategoryProvider } from "./(admin)/admin/dashboard/upload/categorycontext";
import { DocumentProvider } from "./(admin)/admin/dashboard/upload/context";
import { UserProvider } from "./context";
import { AdminAuthProvider } from "./(admin)/admin/context";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "E-Library",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <meta charSet="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            </head>
            <body>
                <AdminAuthProvider>

                    <AuthProvider>
                        <UserProvider>

                            <DocumentProvider>
                                <CategoryProvider>
                                    <Notification />
                                    {children}
                                </CategoryProvider>
                            </DocumentProvider>
                        </UserProvider>

                    </AuthProvider>
                </AdminAuthProvider>

            </body>
        </html>
    );
}
